
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mehja
 */
public class SellBooksForm extends javax.swing.JFrame {

  
     int uId=FirstPage.UserID;
     //System.out.println(uId);
     int POSTID;
    /**
     * Creates new form BooksInfo
     */
    public SellBooksForm() {
        initComponents();
        setSize(1047,739);
        setLocation(360,180);
    }
    public void closePage(){
        WindowEvent wev = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(wev);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane3 = new javax.swing.JEditorPane();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Book Name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 180, 140, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Book Price:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 330, 130, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Writer:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 250, 74, 29);

        jScrollPane1.setViewportView(jEditorPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(370, 170, 581, 41);

        jScrollPane2.setViewportView(jEditorPane2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(370, 250, 581, 42);

        jScrollPane3.setViewportView(jEditorPane3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(370, 330, 581, 39);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Create ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(520, 590, 160, 54);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Description:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 410, 125, 29);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(370, 410, 580, 120);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("<html><u>Create Post</u></html>");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 40, 250, 44);

        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/is.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(980, 20, 40, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1stBack.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1060, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
             LocalDateTime date = LocalDateTime.now();  
            
            try
            {
                
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;user=sa;password=1234567";
            Connection con = DriverManager.getConnection(url);
           
            
            String sql2 = "Insert into [Post]"+"(PostTime, Price, UserId,ApproveStatus,AdminId)"+"values(?,?, ?,?,1)";
            
           
             
            PreparedStatement pst = con.prepareStatement(sql2);
        //    PreparedStatement pst2 = con.prepareStatement(sql);
            
         //   pst2.setString(1, jEditorPane1.getText());  
         //   pst2.setString(2, jEditorPane2.getText());    
          //  pst2.setString(3, jTextField2.getText());
          //  pst2.setString(4, 6);
            String st= jEditorPane3.getText();
            int price=Integer.parseInt(st);
            if(st==null)
            {JOptionPane.showMessageDialog(null, "Fill up everythig");}
            else { 
            String dt=date.toString();
            pst.setString(1, dt);
           // pst.setDate(1, date); 
            pst.setInt(2, price); 
            pst.setInt(3, uId); 
            pst.setInt(4, 0);
            pst.executeUpdate();
            
            GET_POST_ID();
           // pst2.executeUpdate();
        
               String sql = "Insert into [Book]"+"(BookName,Writer,Description,PostId)"+"values(?, ?, ?, ?)";
               PreparedStatement pst2 = con.prepareStatement(sql);
               
              pst2.setString(1, jEditorPane1.getText());  
              pst2.setString(2, jEditorPane2.getText());    
              pst2.setString(3, jTextField2.getText());
              pst2.setInt(4, POSTID);
               
            
               JOptionPane.showMessageDialog(null, "Successfully Created");
               SellBooksForm.Succes field= new  SellBooksForm.Succes();
               field.setVisible(true);
               //setVisible(false);
                jEditorPane1.setText("");
                jEditorPane2.setText("");
                jEditorPane3.setText("");
                jTextField2.setText("");
               
                
                 pst2.executeUpdate();
            }
            /* String sql3= "Insert into [Post]"+"(BookName,Writer,Description, PostId)"+"values(?,?,?, ?)";
               PreparedStatement pst2 = con.prepareStatement(sql);
               
               pst2.setString(1, jEditorPane1.getText());  
               pst2.setString(2, jEditorPane2.getText());    
              pst2.setString(3, jTextField2.getText());
              pst2.setInt(4, POSTID);
               
               
               JOptionPane.showMessageDialog(null, "Successfully Created");
               SellBooksForm.Succes field= new  SellBooksForm.Succes();
               field.setVisible(true);
               //setVisible(false);
                jEditorPane1.setText("");
                jEditorPane2.setText("");
                jEditorPane3.setText("");
                jTextField2.setText("");  */
            
                 
            con.close();
            new Home().setVisible(true);
            closePage();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 

            
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        closePage();
    }//GEN-LAST:event_jButton3ActionPerformed
/*
 public void Get_User_ID()
    {
      
            String UserMail="ms";
            
            try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "1234567");
            
                   
           // System.out.println("DATABASE NAME IS:" + connection.getMetaData().getDatabaseProductName());
          
            Statement statement = connection.createStatement();
          
            ResultSet resultSet = statement
                    .executeQuery("SELECT UserId FROM [User]  WHERE Email = 'ms'");
           
         
            while (resultSet.next()) {
                
               UserID=resultSet.getInt("UserId");
               
            }
            System.out.println(UserID);
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
            
            
            
           
           // String sql="SELECT UserId FROM UserINFO where Email= 'ms'";
           
        
          
    }
 */ 
 public void  GET_POST_ID()
 {
     
            //USER EMAIL FROM LOGIN PAGE
          
           // String UserMail="ms";
            ConnectMSSQL cnobj = new ConnectMSSQL();
        cnobj.connectDB();
            try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "1234567");
            
                  
          
            Statement statement = connection.createStatement();
          
            ResultSet resultSet = statement
                    .executeQuery("SELECT PostId FROM [Post]  WHERE UserId='"+uId+"'");
           
         
            while (resultSet.next()) {
                
               POSTID=resultSet.getInt("PostId");
               
            }
            System.out.println("POst ID"+POSTID);
            
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
            
            

 }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellBooksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellBooksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellBooksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellBooksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellBooksForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JEditorPane jEditorPane3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables


private static class Succes {

        public Succes() {
        }

        private void setVisible(boolean b) {
           
        }
    }
}
