

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mehja
 */
public class UpdatePayment extends javax.swing.JFrame {
DefaultListModel defaultListModel=new DefaultListModel();
        String[] columnNames = {"Order No","User id","BOOK NAME", "WRITER", "PRICE", "Order date"};
     DefaultTableModel model = new DefaultTableModel();
     
    int ORDERID;
    /**
     * Creates new form BookQuery
     */
    public UpdatePayment() {
        initComponents();
        Show_All_Unupdated_Payment();
        setSize(1047,739);
        setLocation(360,180);
    }
    public void closePage(){
        WindowEvent wev = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(wev);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(50, 150, 940, 390);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Update Payment Status");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 40, 440, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Payment received");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 600, 250, 40);

        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/is.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(980, 20, 40, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1stBack.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1080, 700));
        jLabel2.setMinimumSize(new java.awt.Dimension(1080, 700));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1080, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime date = LocalDateTime.now();  
        try
            {
                
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;user=sa;password=1234567";
            Connection con = DriverManager.getConnection(url);
           
            String dt=date.toString();
            
            String sql = "UPDATE [Payment] SET PaymentDate='"+dt+"'";
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.executeUpdate();
            
            
            String sql3 = "UPDATE [Payment] SET PaymentStatus = 1 where OrderId="+ORDERID+"";
           PreparedStatement pst2 = con.prepareStatement(sql3);
           pst2.executeUpdate();
            
            
            con.close();
            new AdminPanel().setVisible(true);
            closePage();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        closePage();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         int x=jTable1.getSelectedRow();
        //int y=jTable1.getSelectedColumn();
       // String Data=jTable1.getComponentAt(x, 0).toString();
        String tl=model.getValueAt(x, 0).toString();
        ORDERID=Integer.parseInt(tl);
        System.out.println(tl);
        

    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    
    public void Show_All_Unupdated_Payment()
   {
         jTable1.setModel(model);
          try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectDB;selectMethod=cursor", "sa", "1234567");
            
                   
           // System.out.println("DATABASE NAME IS:" + connection.getMetaData().getDatabaseProductName());
          
            Statement statement = connection.createStatement();
          
            ResultSet resultSet = statement
                   .executeQuery("SELECT [Order].OrderId,[Order].UserId,[Book].BookName, [Book].Writer,[Post].Price,[Order].OrderDate  from [Order] inner join [Post] on [Order].PostId=[Post].PostId INNER JOIN [Book] ON [Book].PostId=[Order].PostId INNER JOIN [Payment] ON [Payment].OrderId=[Order].OrderId where [Payment].PaymentStatus=0");
           
             model.setColumnIdentifiers(columnNames);
            
         //   BOOK NAME", "WRITER", "PRICE", "DESCRIPTION
            String BookName, Writer, OrderDate;
            int Price,OrderId,UserId;
            
            //System.out.println("1");
            while (resultSet.next()) 
            {
                OrderId=resultSet.getInt("OrderId");
                UserId=resultSet.getInt("UserId");
                BookName=resultSet.getString("BookName");
                Writer=resultSet.getString("Writer");
                Price=resultSet.getInt("Price");
                OrderDate=resultSet.getString("orderDate");
               model.addRow(new Object[]{OrderId,UserId,BookName, Writer, Price, OrderDate});
               
               
               
            }
            //System.out.println("Last");
            connection.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
   }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatePayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
